GET http://localhost:8099/test
Accept: application/json

### add user
POST http://localhost:8099/user
Content-Type: application/json

{
  "name": "vincent",
  "age": 12
}

### delete user
DELETE http://localhost:8099/user/19
Content-Type: application/json


### user list
GET http://localhost:8099/user
Content-Type: application/json

{
  "pageIndex": 1,
  "pageSize": 10
}

###