GET http://localhost:8099/test
Accept: application/json

### add user
POST http://localhost:8099/user
Content-Type: application/json

{
  "name": "vincent",
  "age": 12
}

### delete user
DELETE http://localhost:8099/user/19
Content-Type: application/json


### user list
GET http://localhost:8099/user
Content-Type: application/json

{
  "pageIndex": 1,
  "pageSize": 10
}


### websocket
WEBSOCKET ws://localhost:8099/chicken/socket?erp=jichi
Content-Type: application/json // used only for IDE highlighting.
// Highlighting is applied for each message independently.


{
  "message": "Send when the WebSocket connection is opened"
}
=== wait-for-server
{
  "message": "Wait for the server message and send the current message as response"
}
===
{
  "message": "Send after previous message without waiting for the server message"
}

###

###