### 注册短信ptrp
POST http://localhost:8080/nls/web/sms-code/send-for-register
Content-Type: application/x-www-form-urlencoded

mobile=123

### json格式
POST http://localhost:8080/nls/web/sms-code/send-for-register
Content-Type: application/json

{
  "mobile": "12345678904"
}