GET http://localhost:8080/myworld/hello1
Accept: application/json

###

GET http://localhost:8080/myworld/count
Accept: application/json

###

GET http://localhost:8080/myworld/query?mobile=1
Accept: application/json

###

GET http://localhost:8080/myworld/query
Accept: application/json

###